
//@MinimalApiAot_HostAddress = http://localhost:8080
//http://localhost:5088 locahost開發
// aot image http://localhost:8080,
// docker run -d -p 8080:8080 --name minimal-api chihkang/minimalapiaot:arm64

#### get request Hello World!
GET {{MinimalApiAot_HostAddress}}/
Accept: application/json

#### get request system time
GET {{MinimalApiAot_HostAddress}}/time/
Accept: application/json

### get mongodb health
GET {{MinimalApiAot_HostAddress}}/api/mongodb/health
Accept: application/json

### get api/users
GET {{MinimalApiAot_HostAddress}}/api/users
Accept: application/json

### get api/users/{id}
GET {{MinimalApiAot_HostAddress}}/api/users/67283eee447a55a757f87db8
Accept: application/json

### get api/users/by-email/{email}
GET {{MinimalApiAot_HostAddress}}/api/users/by-email/chihkang@me.com
Accept: application/json

### delete api/users/{id}
DELETE {{MinimalApiAot_HostAddress}}/api/users/{id}
Accept: application/json

### create user api/users
POST {{MinimalApiAot_HostAddress}}/api/users
Accept: application/json

### update api/user/{id}
PUT {{MinimalApiAot_HostAddress}}/api/users
Accept: application/json