namespace MinimalApiAot.Models.Entities;

/// <summary>
/// Represents a position change event (buy/sell/replace) for a stock
/// </summary>
public class PositionEvent
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    [JsonPropertyName("_id")]
    public ObjectId Id { get; set; }

    /// <summary>
    /// Unique operation ID generated by iOS client (UUID format)
    /// </summary>
    [BsonElement("operationId")]
    [JsonPropertyName("operationId")]
    public required string OperationId { get; set; }

    /// <summary>
    /// Reference to the user who owns this position event
    /// </summary>
    [BsonElement("userId")]
    [BsonRepresentation(BsonType.ObjectId)]
    [JsonPropertyName("userId")]
    public ObjectId UserId { get; set; }

    /// <summary>
    /// Reference to the stock being traded
    /// </summary>
    [BsonElement("stockId")]
    [BsonRepresentation(BsonType.ObjectId)]
    [JsonPropertyName("stockId")]
    public ObjectId StockId { get; set; }

    /// <summary>
    /// Type of operation: BUY, SELL, or REPLACE
    /// </summary>
    [BsonElement("type")]
    [JsonPropertyName("type")]
    [BsonRepresentation(BsonType.String)]
    public PositionEventType Type { get; set; }

    /// <summary>
    /// When the trade was executed
    /// </summary>
    [BsonElement("tradeAt")]
    [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
    [JsonPropertyName("tradeAt")]
    public DateTime TradeAt { get; set; }

    /// <summary>
    /// When the event record was created
    /// </summary>
    [BsonElement("createdAt")]
    [BsonDateTimeOptions(Kind = DateTimeKind.Utc)]
    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Quantity held before this operation
    /// </summary>
    [BsonElement("quantityBefore")]
    [BsonRepresentation(BsonType.Decimal128)]
    [JsonPropertyName("quantityBefore")]
    public decimal QuantityBefore { get; set; }

    /// <summary>
    /// Quantity held after this operation (should equal quantityBefore + quantityDelta for BUY/SELL)
    /// </summary>
    [BsonElement("quantityAfter")]
    [BsonRepresentation(BsonType.Decimal128)]
    [JsonPropertyName("quantityAfter")]
    public decimal QuantityAfter { get; set; }

    /// <summary>
    /// Change in quantity (positive for BUY, negative for SELL)
    /// </summary>
    [BsonElement("quantityDelta")]
    [BsonRepresentation(BsonType.Decimal128)]
    [JsonPropertyName("quantityDelta")]
    public decimal QuantityDelta { get; set; }

    /// <summary>
    /// Currency of the transaction (TWD or USD)
    /// </summary>
    [BsonElement("currency")]
    [JsonPropertyName("currency")]
    [BsonRepresentation(BsonType.String)]
    public Currency Currency { get; set; }

    /// <summary>
    /// Total cost basis before this operation (passed from iOS)
    /// </summary>
    [BsonElement("totalCostBefore")]
    [BsonRepresentation(BsonType.Decimal128)]
    [JsonPropertyName("totalCostBefore")]
    public decimal TotalCostBefore { get; set; }

    /// <summary>
    /// Total cost basis after this operation (passed from iOS, validated by service)
    /// </summary>
    [BsonElement("totalCostAfter")]
    [BsonRepresentation(BsonType.Decimal128)]
    [JsonPropertyName("totalCostAfter")]
    public decimal TotalCostAfter { get; set; }

    /// <summary>
    /// Price per unit for this transaction
    /// </summary>
    [BsonElement("unitPrice")]
    [BsonRepresentation(BsonType.Decimal128)]
    [JsonPropertyName("unitPrice")]
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Source of the event (e.g., "ios", "android", "web")
    /// </summary>
    [BsonElement("source")]
    [JsonPropertyName("source")]
    public required string Source { get; set; }

    /// <summary>
    /// Version of the app that created this event
    /// </summary>
    [BsonElement("appVersion")]
    [JsonPropertyName("appVersion")]
    public required string AppVersion { get; set; }
}
