namespace MinimalApiAot.Models.DTO;

/// <summary>
/// Request to create a new position event
/// </summary>
public record CreatePositionEventRequest
{
    /// <summary>
    /// Unique operation ID generated by iOS client (UUID format)
    /// </summary>
    public required string OperationId { get; init; }

    /// <summary>
    /// User ID who owns this position event
    /// </summary>
    public required string UserId { get; init; }

    /// <summary>
    /// Stock ID being traded
    /// </summary>
    public required string StockId { get; init; }

    /// <summary>
    /// Type of operation: BUY, SELL, or REPLACE
    /// </summary>
    public required PositionEventType Type { get; init; }

    /// <summary>
    /// When the trade was executed
    /// </summary>
    public required DateTime TradeAt { get; init; }

    /// <summary>
    /// Quantity held before this operation
    /// </summary>
    public required decimal QuantityBefore { get; init; }

    /// <summary>
    /// Quantity held after this operation
    /// </summary>
    public required decimal QuantityAfter { get; init; }

    /// <summary>
    /// Change in quantity (positive for BUY, negative for SELL)
    /// </summary>
    public required decimal QuantityDelta { get; init; }

    /// <summary>
    /// Currency of the transaction (TWD or USD)
    /// </summary>
    public required Currency Currency { get; init; }

    /// <summary>
    /// Total cost basis before this operation
    /// </summary>
    public required decimal TotalCostBefore { get; init; }

    /// <summary>
    /// Total cost basis after this operation
    /// </summary>
    public required decimal TotalCostAfter { get; init; }

    /// <summary>
    /// Price per unit for this transaction
    /// </summary>
    public required decimal UnitPrice { get; init; }

    /// <summary>
    /// Source of the event (e.g., "ios", "android", "web")
    /// </summary>
    public required string Source { get; init; }

    /// <summary>
    /// Version of the app that created this event
    /// </summary>
    public required string AppVersion { get; init; }
}
