namespace MinimalApiAot.Models;

[JsonSourceGenerationOptions(WriteIndented = false)]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(List<User>))]
[JsonSerializable(typeof(UserSettings))]
[JsonSerializable(typeof(ObjectId))]
[JsonSerializable(typeof(StockMinimalDto))]
[JsonSerializable(typeof(IEnumerable<StockMinimalDto>))]
[JsonSerializable(typeof(List<StockMinimalDto>))]
[JsonSerializable(typeof(UpdateStockPriceResponse))]
[JsonSerializable(typeof(Stock))]
[JsonSerializable(typeof(Portfolio))]
[JsonSerializable(typeof(List<Portfolio>))]
[JsonSerializable(typeof(IEnumerable<Portfolio>))]
[JsonSerializable(typeof(PortfolioStock))]
[JsonSerializable(typeof(PortfolioResponseDto))]
[JsonSerializable(typeof(List<PortfolioResponseDto>))]
[JsonSerializable(typeof(UpdatePortfolioStockDto))]
[JsonSerializable(typeof(List<UpdatePortfolioStockDto>))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateStockQuantityRequest))]
[JsonSerializable(typeof(UpdateStockByIdRequest))]
[JsonSerializable(typeof(UpdateStockByNameRequest))]
[JsonSerializable(typeof(BatchUpdateStockPriceRequest))]
[JsonSerializable(typeof(BatchUpdateStockPriceResponse))]
[JsonSerializable(typeof(UpdateStockPriceItem))]
[JsonSerializable(typeof(List<UpdateStockPriceItem>))]
[JsonSerializable(typeof(ApiResponse<Portfolio>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(PortfolioDailyValueResponse))]
[JsonSerializable(typeof(TimeRange))]
[JsonSerializable(typeof(DateTimeRange))]
// PositionEvent types
[JsonSerializable(typeof(PositionEvent))]
[JsonSerializable(typeof(List<PositionEvent>))]
[JsonSerializable(typeof(PositionEventType))]
[JsonSerializable(typeof(Currency))]
[JsonSerializable(typeof(CreatePositionEventRequest))]
[JsonSerializable(typeof(UpdatePositionEventRequest))]
[JsonSerializable(typeof(PositionEventResponseDto))]
[JsonSerializable(typeof(List<PositionEventResponseDto>))]
[JsonSerializable(typeof(PaginationRequest))]
[JsonSerializable(typeof(PaginatedResponse<PositionEventResponseDto>))]
[JsonSerializable(typeof(PositionEventQueryRequest))]
[JsonSerializable(typeof(PositionEventCreateResult))]
[JsonSerializable(typeof(PositionEventUpdateResult))]
[JsonSerializable(typeof(PositionEventDeleteResult))]
[JsonSerializable(typeof(PositionEventErrorType))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(SuccessResponse))]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}